#Python Important Programs

write a python program to print the following pattern<br>
$*$ <br>
$**$ <br>
$***$<br>
$****$<br>
$*****$<br>

In [3]:
n = int(input("Enter the number of rows"))  
for i in range(0, n):
  for j in range(0, i + 1):
    print("* ", end="")
  print()


Enter the number of rows5
* 
* * 
* * * 
* * * * 
* * * * * 


Write a python program to print prime numbers up to n

In [4]:
start_val = 1
n = int(input("Enter the n number:"))
for num in range(start_val, n+1):
    if(num>1):
        for i in range(2,num):
            if(num%i)==0:
                break
        else:
            print(num)


Enter the n number:20
2
3
5
7
11
13
17
19


Write a python program to find sum of n natural numbers using for loop

In [9]:
sum=0
n = int(input("Enter n"))
for i in range(1,n+1):
  sum=sum+i
print("The sum is:",sum)  

Enter n10
The sum is: 55


Write a python program to find largest of three numbers

In [10]:
num1 = float(input("Enter number 1: ")) 
num2 = float(input("Enter number 2: ")) 
num3 = float(input("Enter number 3: "))
big=num1
if (big<num2): big=num2
if (big<num3): big=num3

print("The largest among the three is : ",big)


Enter number 1: 20
Enter number 2: 30
Enter number 3: 10
The largest among the three is :  30.0


Write a python program to compute addition, multiplication  of matrices using numpy

In [17]:
import numpy as np
A = np.array([[1, 1, 1], [1, 1, 1],[1,1,1]])
B = np.array([[1, 1, 1], [1, 1, 1],[1,1,1]])
add=A+B
print("Addition is",add)
mul = A.dot(B)
print("Multiplication is",mul)

Addition is [[2 2 2]
 [2 2 2]
 [2 2 2]]
Multiplication is [[3 3 3]
 [3 3 3]
 [3 3 3]]


Write a python program to find maximum element in each column, minimum element in each row and sum of  elements in each row using numpy

In [19]:
import numpy as np  
a = np.array([[1,2,30],[10,15,4]])  
print("The array:",a)  
print("The maximum elements of each column:",a.max(axis = 0))   
print("The minimum element of each row",a.min(axis = 1))  
print("The sum of elements of each row",a.sum(axis = 1))  


The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of each column: [10 15 30]
The minimum element of each row [1 4]
The sum of elements of each row [33 29]


Write a python program to find factorial of a given number using recursion

In [21]:
def factorial(x):
     if x == 1:
        return 1
     else:
        return (x * factorial(x-1))
num = 3
print("The factorial of", num, "is", factorial(num))


The factorial of 3 is 6


Write a python program to demonstrate various list operations

In [26]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
print("Repetition:",list1*2)
print("Concatenation:",list1+list2)
print("membership:",2 in list1)
print("Iteration:")
for i in list1:
  print(i)
print("length:",len(list1)) 

Repetition: [1, 2, 3, 4, 1, 2, 3, 4]
Concatenation: [1, 2, 3, 4, 5, 6, 7, 8]
membership: True
Iteration:
1
2
3
4
length: 4


Write a python program toimplement basic calculator using functions

In [27]:
# Python program for simple calculator
  
# Function to add two numbers 
def add(num1, num2):
    return num1 + num2
  
# Function to subtract two numbers 
def subtract(num1, num2):
    return num1 - num2
  
# Function to multiply two numbers
def multiply(num1, num2):
    return num1 * num2
  
# Function to divide two numbers
def divide(num1, num2):
    return num1 / num2
  
print("Please select operation -\n" \
        "1. Add\n" \
        "2. Subtract\n" \
        "3. Multiply\n" \
        "4. Divide\n")
   
# Take input from the user 
select = int(input("Select operations form 1, 2, 3, 4 :"))
  
number_1 = int(input("Enter first number: "))
number_2 = int(input("Enter second number: "))
  
if select == 1:
    print(number_1, "+", number_2, "=",
                    add(number_1, number_2))
  
elif select == 2:
    print(number_1, "-", number_2, "=",
                    subtract(number_1, number_2))
  
elif select == 3:
    print(number_1, "*", number_2, "=",
                    multiply(number_1, number_2))
  
elif select == 4:
    print(number_1, "/", number_2, "=",
                    divide(number_1, number_2))
else:
    print("Invalid input")


Please select operation -
1. Add
2. Subtract
3. Multiply
4. Divide

Select operations form 1, 2, 3, 4 :1
Enter first number: 10
Enter second number: 20
10 + 20 = 30


Write a python program to find even numbers in a list

In [28]:
# list of numbers
list1 = [10, 21, 4, 45, 66, 93]
 
# iterating each number in list
for num in list1:
 
    # checking condition
    if num % 2 == 0:
        print(num, end=" ")


10 4 66 